module.exports = [
  'GALAXY-42/SYSTEM/PLANET:{}',
  'GALAXY-42/SYSTEM/PLANET:{Message}',
  'GALAXY-42/System/PLANET:{Message}',
  'GALAXY-42/SYSTEM/PLANET{Message}',
  'LONGGALAXY-42/SYSTEM/PLANET:{Message}',
  'GALAXY-4/SYSTEM/PLANET:{Message}',
  'GALAXY-4815162342/SYSTEM/PLANET:{Message}',
  'GALAXY-42/THE-SOLAR-SYSTEM/PLANET:{Message}',
  'GALAXY-42/-SYSTEM/PLANET:{Message}',
  'GALAXY-42/SYSTEM1/PLANET:{Message}',
  'GALAXY-42/SYS--TEM/PLANET:{Message}',
  'GALAXY-42/SYSTEM/OOP:{Message}',
  'GALAXY-42/SYSTEM/FP:{Message}',
  'GALAXY-42/SYSTEM/DDOUBLE:{Message}',
  'GALAXY-42/SYSTEM/OOOPS:{Message}',
  'GALAXY-42/SYSTEM/PLANET:{Simple text... @null == undefined@}',
  'GALAXY-42/SYSTEM/PLANET:{@typeof null@@typeof typeof null@}',
]
