module.exports = [
  // '@',
  // '[]',
  // '',
  'XX-00/AA/ZXCXS:{@asdasdas12eQWD#@cx_)_+!@#+_!)@$_++_}',
  // 'NULL-23212321/TRUE/TRUE:{:{\\@/@}',
  // 'TRUE-23212321/TRUE/TRUE:{:{\\@/@}',
  // 'FALSE-23212321/FALSE/FALSE:{:{\\@/@}',
  // 'GASDASD-23212321/SYSTEM/PLANET:{ @ @ @ @ }',
  // 'GASDASD-23212321/-SYSTEM/PLANET:{asdasdasdasd}',
  // 'GASD-232/SYSTEM/P.LANET:{}',
  // 'GASD-232/SYSTEM_/PLANET:{}',
  // 'GASD-2/SYSTEM/PLANET:{}',
  // 'G-42/SYSTEM/PLANET:{}',
  // 'GALAXY42/SYSTEM/PLANET:{}',
  // 'GALAXY-42/SYSTEM/PLANET:{}',
  // 'GALAXY-42/SYSTEM/:{Message}',
  // 'GALAXY-42//PLANET:{Message}',
  // 'GALAXY-/SYSTEM/PLANET:{Message}',
  // '-42/SYSTEM/PLANET:{Message}',
  // '/SYSTEM/PLANET:{Message}',
  // '/SYSTEM/PLANET     :{Message}',
  // '/SYSTEM/    PLANET:{Message}',
  // 'GALAXY-42//PLANET:{Message}    ',
  // '      GALAXY-42//PLANET:{Message}'
]
